### ISSUE TITLE
Agenda - DevOps Mutualization SIG Meeting - Thursday 22 July 2021

### ISSUE THREAD

**Issue by mcleo-d** [finos/devops-mutualization#32]
## Date
Thursday 22 July 2021 - 12pm EST / 5pm UK

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Approve [previous meeting minutes](https://github.com/finos/devops-mutualization/issues/30)
- [x] Introduction to CatchIT FINOS contribution and Goldman Sachs team (10mins) - https://github.com/finos/community/issues/124 - @gunwantsingh
- [x] #33
  - Private repo for the WG to collaborate has been setup - https://github.com/finos-labs/devops-mutualization-automated-change-deployment
  - WG members invited to join team - https://github.com/orgs/finos-labs/teams/devops-mutualization-automated-change-deployment
- [x]  https://github.com/finos/devops-mutualization/issues/26#issuecomment-884964396 - update and progress
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes

- Attendees
 - James McLeod FINOS
 - Amol Shukla - MS
 - Eduardo Santos - Banco Brazil (?)
 - Christopher Phang - CodeThink
 - Aniruddha Bhattacharjee - GS
 - Anish Gupta - GS
 - Ashok Singh - JPMC
 - Jane Gavronsky - FINOS
 - Richard Wagner - CodeThink
 - Tristan Maat - CodeThink

- Agenda review
- Roll call
- Notices
 - Guidelines for project leads
 - Antitrust policy
 - Recording notice
- Approved minutes from June 17 2021 meeting by silent consent
- CatchIT FINOS contribution from Goldman Sachs - Anish, Anirud (link in Agenda)
 - Tool to run inside CI/CD pipelines to identify hardcoded secrets & sensitive data
 - Gap identified that embedded secrets were not identified during SDLC
 - Pattern-based, minimal execution time (1 second), minimize false positives, categorize findings
 - Existing solutions had high rates of false positives
 - Block pipelines when appropriate based on findings
 - Help initiate cultural shift, knowing that CatchIT would find problems introduced by commits
 - Mandatory for all pipelines, pipelines blocked by "high confidence" positive findings
 - In production for 1.5 years
 - False positive rate ~15%; some regexes less than 5%
 - Median execution time 0.5s, 80% of pipelines run it in < 1s
 - Has identified > 7k findings
 - Q: Is it stack-specific? A: No
 - Q: How you use these findings for shift-left, provide visibility in IDE or during PR? A: Primarily during pipeline now
 - Discussion around process for contribution
- Automated Change Deployment Working Group
 - Private repo has been created (link in Agenda)
 - Invite to join the team (link in Agenda)
 - Talk about FINOS Labs' relationship to FINOS
- DevOps World 2021 Panel Discussion Preparation and Planning (link in Agenda)
 - Review panel members
 - Review the questions for the panel
  - What is DevOps Mutualization?
  - Key challenges & lessons around DevOps in banks?
  - How does your org share lessons around industry peers?
 - Discussion around publicizing the panel

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=md62056638ba05fbea86b9582df94f807

### Dial-in
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 662 6070

**Github Repo:** https://github.com/finos/devops-mutualization/

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by mcleo-d** [comment]
@sotiraki-sima-gs, @gunwantsingh, @aniitg and @anirudnits

Please mention in the comments below whether you would like 10 mins on the agenda to socialize CatchIT with the wider DevOps SIG.

Kind regards,

James 🚀

**Comment by gunwantsingh** [comment]
@mcleo-d Thank you for the opportunity. 10 minutes is fine. Not sure if we can get more, like 20 minutes?
We'd be presenting with 2-3 slides and taking questions also.

**Comment by mcleo-d** [comment]
> @mcleo-d Thank you for the opportunity. 10 minutes is fine. Not sure if we can get more, like 20 minutes?
> We'd be presenting with 2-3 slides and taking questions also.

Hi @gunwantsingh - I have allocated you 10 minutes on the agenda to introduce the project and team. This way we can gauge the appetite of the group for a 20 minute deep dive in the future.

I hope this works for you?

James.

**Comment by mcleo-d** [comment]
Hey all 👋🏻

**Comment by cphang99** [comment]
Hi!

**Comment by ashukla13** [comment]
hi

**Comment by anirudnits** [comment]
Hi!

**Comment by TLATER** [comment]
o/

**Comment by aniitg** [comment]
Hello!

**Comment by eduardosan** [comment]
Hi

**Comment by jgavronsky** [comment]
Jane / FINOS here

**Comment by awallgren** [comment]
Hi everyone!

**Comment by RichardWagener365** [comment]
Hi

**Comment by awallgren** [comment]
Added minutes -- for some reason my outline was flattened even though I used the same format as in previous meetings. Have to run to another meeting, will try to check back later to see if I can fix the formatting.
