### ISSUE TITLE
Agenda - DevOps Mutualization SIG Meeting - Thursday 19 August 2021

### ISSUE THREAD

**Issue by mcleo-d** [finos/devops-mutualization#34]
## Date
Thursday 19 August 2021 - 12pm EST / 5pm UK

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Approve [previous meeting minutes](https://github.com/finos/devops-mutualization/issues/32)
- [x] Automated Change Deployment Working Group Recap : https://github.com/finos/devops-mutualization/issues/33
- [x] Panel Discussion Recap : https://github.com/finos/devops-mutualization/issues/26
- [ ] _Add Items Here_
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=md62056638ba05fbea86b9582df94f807

### Dial-in
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 662 6070

**Github Repo:** https://github.com/finos/devops-mutualization/

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by ashukla13** [comment]
hello!

**Comment by cphang99** [comment]
Hi!

**Comment by RichardWagener365** [comment]
Hi

**Comment by awallgren** [comment]
Hi all!
