### ISSUE TITLE
DevOps Mutualization SIG Meeting - January 20, 2022

### ISSUE THREAD

**Issue by mcleo-d** [finos/devops-mutualization#39]
## Date
20 JAN 2022 - 12pm ET / 5pm GMT

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Approve previous meeting minutes
- [x] Announce outcome of vote - Proposed changes to SIG operating model in 2022 - use public Github repos and discussions - vote to open SIG work and initiatives as default taken here (_but with the option of private_) - https://github.com/finos/devops-mutualization/issues/38#issuecomment-996024508
- [x] [FINOS GitProxy](https://github.com/finos/git-proxy) update and community Q&A with @grovesy, Project Lead Maintainer from Citi (20 to 25 mins)
- [x] Determine if DevOps Mutualization is a good venue for a Waltz demo as discussed with @davidwatkins73 in https://github.com/finos/waltz/issues/5787
- [x] Question asked on Waltz project meeting : What are the deployment options being used across other banks and projects? cc @davidwatkins73 https://github.com/finos/waltz/issues/5787
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=md62056638ba05fbea86b9582df94f807

### Dial-in
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 662 6070

**Github Repo:** https://github.com/finos/devops-mutualization/

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by mcleo-d** [comment]
Hi @ashukla13 and @robbkeayes 

I have created the DevOps Mutualization agenda for Thursday 20th January 2022 at 12pm ET / 5pm GMT as @grovesy from Citi would like to update the DevOps Mutualization community on the progress made to [GitProxy](https://github.com/finos/git-proxy).

I hope starting to set the agenda this far in advance helps.

Kind regards,

James.

**Comment by ashukla13** [comment]
hello!

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by RichardWagener365** [comment]
Hi

**Comment by kriscanonical** [comment]
hello !

**Comment by cm-howard** [comment]
Hey 👋🏼

**Comment by davidwatkins73** [comment]
Hi

**Comment by pholleran** [comment]
![image](https://user-images.githubusercontent.com/4007128/150387099-04f5dda6-140b-4f0b-8eba-cad133ba4c51.png)

**Comment by robbkeayes** [comment]
HI everyone

**Comment by pedroleaoc** [comment]
Hi!

**Comment by jgavronsky** [comment]
Hello, Jane @ FINOS here

**Comment by tcraigjohnson** [comment]
Hello from California

**Comment by brooklynrob** [comment]
Here.
